### ISSUE TITLE
Better link to LuaJIT bytecode explanation

### ISSUE THREAD

**Issue by Zireael07** [WuBingzheng/build-lua-in-rust#3]
The link in the site goes to a general LuaJIT wiki.

This alternate wiki does describe the bytecode https://kress95.github.io/luajit-wiki/Bytecode/

**Comment by WuBingzheng** [comment]
Thanks very much .

It seems that the current link `http://wiki.luajit.org/Bytecode-2.0` is broken and redirected to luajit's home page.

Is your link `https://kress95.github.io/luajit-wiki/Bytecode/` official site?

**Comment by Zireael07** [comment]
AFAIK it's not the official site, but at least it describes the bytecode instead of redirecting

**Comment by WuBingzheng** [comment]
I choose this `https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_bc.h`.

Thanks for the remind.
