### ISSUE TITLE
1.4章好像漏了set_stack方法

### ISSUE THREAD

**Issue by NayamiOR** [WuBingzheng/build-lua-in-rust#4]
虚拟机执行部分：`execute`方法引用到了`self.set_stack`。
这个在仓库代码和书后面章节都有提到，但是在1.4部分里没有写。

**Comment by WuBingzheng** [comment]
确实漏了。
看rust的源码里是用ANCHOR标记了的，所以应该是写第一版的时候是介绍了这个函数；后面修订的时候，可能觉得这个函数比较简单，为了减少篇幅，就给删掉了。
既然你问了，看来还是有必要介绍下的。我有空了再加上。
这个函数比较简单，可以参考下[对应的rust源码](https://github.com/WuBingzheng/build-lua-in-rust/blob/main/listing/ch01.hello_world/src/vm.rs#L67)。

多谢反馈！
